### ISSUE TITLE
0.4.0 - Inventory/Mirror fail

### ISSUE THREAD

**Issue by LonelyWolffe** [articustd/big#22]
So, within one day I've managed to bug the inventory, started after I bought some vitamins. Error: cannot execute macro <<invMacro>>: r[0] is undefined
Day 3, broke the mirror when I went to look at it after sleeping.  Error: cannot execute macro <<playerFluffMacro>>: can't convert undefined to object

I don't know if what I did was the problem or it's just the version, but I was enjoying the new UI elements for those nice 5 minutes.

Save file included - Compressed to .zip because .save is invalid for whatever reason
[Bigger-is-better-is-bugged.zip](https://github.com/articustd/big/files/7836530/Bigger-is-better-is-bugged.zip)
.

**Comment by articustd** [comment]
Appreciate the save! That'll help figure out what the issue is.

**Comment by articustd** [comment]
Issue should now be resolved for both. If anything else comes up, please report it. Appreciate the help!
