### ISSUE TITLE
Corrupted Save 6.0

### ISSUE THREAD

**Issue by jsb5468** [articustd/big#41]
Cause is unknown, save starts at mirror screen, but it cant initialize anything with the macro functions

{"name":"Min","stats":{"strg":204,"dex":88,"acc":104,"con":39,"hlth":203,"maxHlth":203},"exp":{"muscle":0,"fat":0,"pawEye":0,"agility":0,"size":0,"skill":0},"measurements":{"height":3178,"bodyFat":0.05000000000000002},"gender":{"penis":0.8500000000000004,"balls":0.26000000000000006,"breasts":false,"vagina":false,"pronouns":0,"type":"Male"},"capacity":{"stomachMax":23464.96330574155,"stomach":0,"testiMax":2582.964953035116,"testi":0},"species":"Dragon","attacks":[4,2],"learnedAttacks":[1,0,4,2],"credits":860,"skills":[2],"skillPoints":164,"inv":[{"id":0,"qty":14},{"id":7,"qty":27}]}

[bigger-is-better-corrupted-save-6.0.txt](https://github.com/articustd/big/files/8145655/bigger-is-better-corrupted-save-6.0.txt)

Change Moveset Works
Travel Works
Look In Mirror Works
All Gym Stuff works
Buy items Works
Go Home Works

Cant Enter Combat
Cant Rest
Cant Use Items

**Comment by jsb5468** [comment]
Upon Entering Combat:
An error has occurred. You may be able to continue, but some parts may not work properly.

Error: cannot execute macro <<enemyMacro>>: skills is not defined.

Stack Trace:
wikiWithOptions@https://articustd.github.io/big/:440:48325
wiki@https://articustd.github.io/big/:440:48509
handler/</<@https://articustd.github.io/big/ line 440 > eval:9:33693
value/<@https://articustd.github.io/big/:440:198706
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

**Comment by jsb5468** [comment]
Upon Sleeping
An error has occurred. You may be able to continue, but some parts may not work properly.

Error: macro <<restMacro>> does not exist.

Stack Trace:
wikiWithOptions@https://articustd.github.io/big/:440:48325
wiki@https://articustd.github.io/big/:440:48509
handler/</<@https://articustd.github.io/big/ line 440 > eval:9:33318
value/<@https://articustd.github.io/big/:440:198706
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

**Comment by jsb5468** [comment]
Upon using items
An error has occurred. You may be able to continue, but some parts may not work properly.

Error: getMaxHealth is not defined.

Stack Trace:
handler/</o</<@https://articustd.github.io/big/ line 440 > eval:9:38958
handler/</o<@https://articustd.github.io/big/ line 440 > eval:9:39035
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

**Comment by articustd** [comment]
Try now, there was a bit of conversion done in the background and I didn't get everything. Sorry! @jsb5468

**Comment by jsb5468** [comment]
It appears to work now!

**Comment by jsb5468** [comment]
When getting attacked in the metro

An error has occurred. You may be able to continue, but some parts may not work properly.

Error: findSize is not defined.

Stack Trace:
handler/</<@https://articustd.github.io/big/ line 440 > eval:9:33991
value/<@https://articustd.github.io/big/:440:199087
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

**Comment by articustd** [comment]
_Sigh_... I did a really bad job at catching all these. Should be good now

**Comment by jsb5468** [comment]
When getting attacked in the metro

An error has occurred. You may be able to continue, but some parts may not work properly.

Error: sizes is not defined.

Stack Trace:
handler/</<@https://articustd.github.io/big/ line 440 > eval:9:34094
value/<@https://articustd.github.io/big/:440:199087
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

**Comment by articustd** [comment]
Try now, I hope this is the last one.

**Comment by jsb5468** [comment]
everything works now

**Comment by articustd** [comment]
Awesome! Closing this issue. If anything else comes up, please make another one!
