### ISSUE TITLE
Intermittant error on "looking for trouble

### ISSUE THREAD

**Issue by jsb5468** [articustd/big#44]
An error has occurred. You may be able to continue, but some parts may not work properly.

Error: cannot execute macro <<enemyMacro>>: rollItems is not defined.

Stack Trace:
wikiWithOptions@https://articustd.github.io/big/:440:48325
wiki@https://articustd.github.io/big/:440:48509
handler/</<@https://articustd.github.io/big/ line 440 > eval:9:33806
value/<@https://articustd.github.io/big/:440:198706
onClickFnWrapper/<@https://articustd.github.io/big/:440:45634
dispatch@https://articustd.github.io/big/:57:43064
add/v.handle@https://articustd.github.io/big/:57:41048

assuming it has to do with enemies that instantly surrender

**Comment by articustd** [comment]
Should be fixed now, thank you for your patience and reporting these issues!
